/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/lib')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/lib')['BreadcrumbItem']
    ACard: typeof import('ant-design-vue/lib')['Card']
    ACol: typeof import('ant-design-vue/lib')['Col']
    AConfigProvider: typeof import('ant-design-vue/lib')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/lib')['Dropdown']
    AFlex: typeof import('ant-design-vue/lib')['Flex']
    AImage: typeof import('ant-design-vue/lib')['Image']
    ALayout: typeof import('ant-design-vue/lib')['Layout']
    ALayoutContent: typeof import('ant-design-vue/lib')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/lib')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/lib')['LayoutHeader']
    AMenu: typeof import('ant-design-vue/lib')['Menu']
    AMenuItem: typeof import('ant-design-vue/lib')['MenuItem']
    ARow: typeof import('ant-design-vue/lib')['Row']
    ASpace: typeof import('ant-design-vue/lib')['Space']
    ASubMenu: typeof import('ant-design-vue/lib')['SubMenu']
    ATypographyText: typeof import('ant-design-vue/lib')['TypographyText']
    ATypographyTitle: typeof import('ant-design-vue/lib')['TypographyTitle']
    CloseOutlined: typeof import('@ant-design/icons-vue')['CloseOutlined']
    DoubleRightOutlined: typeof import('@ant-design/icons-vue')['DoubleRightOutlined']
    MenuOutlined: typeof import('@ant-design/icons-vue')['MenuOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
