/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/lib')['Button']
    AConfigProvider: typeof import('ant-design-vue/lib')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/lib')['DatePicker']
    AForm: typeof import('ant-design-vue/lib')['Form']
    AFormItem: typeof import('ant-design-vue/lib')['FormItem']
    AInput: typeof import('ant-design-vue/lib')['Input']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
